### ISSUE TITLE
CPU metrics seem to be host rather than application instance

### ISSUE THREAD

**Issue by DavePickard1234** [DataDog/datadog-cloudfoundry-buildpack#92]
CPU usage metrics seems to show what I'm guessing is the underlying host metrics rather than the metrics from the AI.  Is this intentional?  Is there a way to get the AI metrics into Datadog.  At the moment we're having to use the Tanzu App Metrics to view and don't have a correlated view in Datadog which is hindering our monitoring efforts and from our perspective makes the metrics capability fairly useless.

**Comment by zippolyte** [comment]
Hey @DavePickard1234 

IIUC, you have configured the buildpack in your app with the environment variable `RUN_AGENT=true` to collect CPU metrics, correct ? If so, since the agent is running inside the container itself, alongside the application, I believe you should have the CPU usage of the container itself, not the host.

That being said, I'd advise against using the buildpack in order to collect system metrics, and rather use the [Datadog Cluster Monitoring Tile for VMware Tanzu](https://network.pivotal.io/products/datadog/) instead.
Many new features have been included in recent versions, including the ability to view your application instances as containers directly in the Container List view of the Datadog application. You can visualize the main system metrics directly in this view. 
The tile also includes a firehose nozzle that can collect app metrics directly, and enrich them with lots of tags, like labels and annotations assigned to your apps.

Hope this helps, let us know if you have questions.

**Comment by DavePickard1234** [comment]
Thanks @zippolyte.  I'll look at the Monitoring Tile but is that not for monitoring the entire platform rather than our Apps running within the platform.  My team don't own the platform - just our own Apps within it.

With regards the CPU metrics, TBH I'm not 100% sure what is showing - all I know is that the CPU usage showing in Datadog doesn't match what is shown in the platform App Metrics dashboard.

**Comment by zippolyte** [comment]
Yeah I understand. Usually, the platform admins would install the Cluster Monitoring Tile, and once it's done, any app that you pushed automatically gets its metrics sent into Datadog via the firehose nozzle. I believe those nozzle metrics are what you can see in the App Metrics dashboard.

If this is not possible, I believe it is also possible to push our [firehose nozzle](https://github.com/DataDog/datadog-firehose-nozzle) as an app directly, as long as you have a user with the proper [permissions to log into the firehose](https://github.com/DataDog/datadog-firehose-nozzle#configure-cloudfoundry-uaa-for-firehose-nozzle).
